# Generated by Django 4.2.1 on 2023-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='profile_pic',
            new_name='agent_pic',
        ),
        migrations.AlterField(
            model_name='agents',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
