# Generated by Django 4.2.1 on 2023-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_content',
            field=models.TextField(blank=True),
        ),
    ]
