# Generated by Django 4.2.1 on 2023-05-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='property_images/')),
                ('house_address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('amount', models.IntegerField(blank=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True)),
                ('baths', models.IntegerField(blank=True)),
                ('garages', models.IntegerField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
