# Generated by Django 4.2.1 on 2023-05-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_amenities_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='amenities',
        ),
    ]
