# Generated by Django 4.2.1 on 2023-05-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_propertyimage_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('name',), 'verbose_name_plural': 'properties'},
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='properties.property')),
            ],
        ),
    ]
