# Generated by Django 4.2.1 on 2023-06-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0004_alter_property_options_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agents'),
            preserve_default=False,
        ),
    ]
