# Generated by Django 4.2.1 on 2023-06-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_profile_pic_agents_agent_pic_and_more'),
        ('properties', '0005_property_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agents'),
            preserve_default=False,
        ),
    ]
